CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Brand" (
    "Id" text NOT NULL,
    "BrandName" text NULL,
    "BrandDescription" text NULL,
    CONSTRAINT "PK_Brand" PRIMARY KEY ("Id")
);

CREATE TABLE "Category" (
    "Id" text NOT NULL,
    "CategoryName" text NULL,
    "CategoryDescription" text NULL,
    CONSTRAINT "PK_Category" PRIMARY KEY ("Id")
);

CREATE TABLE "Role" (
    "Id" text NOT NULL,
    "Name" character varying(256) NULL,
    "NormalizedName" character varying(256) NULL,
    "ConcurrencyStamp" text NULL,
    CONSTRAINT "PK_Role" PRIMARY KEY ("Id")
);

CREATE TABLE "Supplier" (
    "Id" text NOT NULL,
    "SupplierName" character varying(50) NOT NULL,
    "Description" text NULL,
    "Street" character varying(50) NOT NULL,
    "City" character varying(30) NOT NULL,
    "Province" character varying(30) NOT NULL,
    "Country" character varying(30) NOT NULL,
    "SalePersonName" character varying(50) NULL,
    "PhoneNumber" text NULL,
    "Email" text NULL,
    CONSTRAINT "PK_Supplier" PRIMARY KEY ("Id")
);

CREATE TABLE "Transaction" (
    "Id" text NOT NULL,
    "Name" text NULL,
    "TransactionId" text NULL,
    "ValidUntil" timestamp without time zone NOT NULL,
    "CreatedDate" timestamp without time zone NOT NULL,
    "ModifiedDate" timestamp without time zone NOT NULL,
    "CreatedById" text NULL,
    "ConfirmedBy" text NULL,
    "TrackingNumber" timestamp without time zone NOT NULL,
    "Type" integer NOT NULL,
    "Status" boolean NOT NULL,
    CONSTRAINT "PK_Transaction" PRIMARY KEY ("Id")
);

CREATE TABLE "UserInfo" (
    "Id" text NOT NULL,
    "OwnerID" text NULL,
    "Username" text NULL,
    "Email" text NULL,
    "Fullname" text NULL,
    "PhoneNumber" text NULL,
    "Address" text NULL,
    "DateOfBirth" timestamp without time zone NOT NULL,
    "DateOfBirthNormalizedString" text NULL,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_UserInfo" PRIMARY KEY ("Id")
);

CREATE TABLE "RoleClaim" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text NULL,
    "ClaimValue" text NULL,
    CONSTRAINT "PK_RoleClaim" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RoleClaim_Role_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Role" ("Id") ON DELETE CASCADE
);

CREATE TABLE "PriceQuote" (
    "Id" text NOT NULL,
    "PriceQuoteOrderNumber" text NULL,
    "SupplierId" text NULL,
    "CreatedDate" timestamp without time zone NOT NULL,
    "ModifiedDate" timestamp without time zone NOT NULL,
    "ModifiedBy" text NULL,
    "Deadline" timestamp without time zone NOT NULL,
    "Description" text NULL,
    "CreatedById" text NULL,
    "PriceQuoteStatus" integer NOT NULL,
    "Type" integer NOT NULL,
    "TotalOrderAmount" numeric NOT NULL,
    "TransactionId" text NULL,
    CONSTRAINT "PK_PriceQuote" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PriceQuote_Supplier_SupplierId" FOREIGN KEY ("SupplierId") REFERENCES "Supplier" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_PriceQuote_Transaction_TransactionId" FOREIGN KEY ("TransactionId") REFERENCES "Transaction" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_PriceQuote_UserInfo_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "UserInfo" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Product" (
    "Id" text NOT NULL,
    "Name" text NULL,
    "BrandId" text NULL,
    "CategoryId" text NULL,
    "CreatedById" text NULL,
    "CreatedDate" timestamp without time zone NOT NULL,
    "ModifiedDate" timestamp without time zone NOT NULL,
    "SellingStrategy" text NULL,
    CONSTRAINT "PK_Product" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Product_Brand_BrandId" FOREIGN KEY ("BrandId") REFERENCES "Brand" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Product_Category_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Category" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Product_UserInfo_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "UserInfo" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "SystemUser" (
    "Id" text NOT NULL,
    "UserInfoId" text NULL,
    "UserName" character varying(256) NULL,
    "NormalizedUserName" character varying(256) NULL,
    "Email" character varying(256) NULL,
    "NormalizedEmail" character varying(256) NULL,
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text NULL,
    "SecurityStamp" text NULL,
    "ConcurrencyStamp" text NULL,
    "PhoneNumber" text NULL,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone NULL,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_SystemUser" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SystemUser_UserInfo_UserInfoId" FOREIGN KEY ("UserInfoId") REFERENCES "UserInfo" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "PurchaseOrder" (
    "Id" text NOT NULL,
    "CreatedDate" timestamp without time zone NOT NULL,
    "ModifiedDate" timestamp without time zone NOT NULL,
    "ModifiedBy" text NULL,
    "PurchaseOrderNumber" text NULL,
    "DeliveryDate" timestamp without time zone NOT NULL,
    "DeliveryAddress" text NULL,
    "Description" text NULL,
    "SupplierId" text NULL,
    "WarehouseLocation" text NULL,
    "CreatedById" text NULL,
    "CreatedByName" text NULL,
    "PriceQuoteOrderId" text NULL,
    "PurchaseOrderStatus" integer NOT NULL,
    "Type" integer NOT NULL,
    "TotalDiscountAmount" numeric NOT NULL,
    "TotalOrderAmount" numeric NOT NULL,
    "PurchaseReceiveNumber" text NULL,
    "TransactionId" text NULL,
    CONSTRAINT "PK_PurchaseOrder" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PurchaseOrder_PriceQuote_PriceQuoteOrderId" FOREIGN KEY ("PriceQuoteOrderId") REFERENCES "PriceQuote" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_PurchaseOrder_Supplier_SupplierId" FOREIGN KEY ("SupplierId") REFERENCES "Supplier" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_PurchaseOrder_Transaction_TransactionId" FOREIGN KEY ("TransactionId") REFERENCES "Transaction" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_PurchaseOrder_UserInfo_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "UserInfo" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "ProductVariant" (
    "Id" text NOT NULL,
    "ProductId" text NULL,
    "Name" text NULL,
    "Price" numeric NOT NULL,
    "Sku" text NULL,
    "Unit" text NULL,
    "Quantity" real NOT NULL,
    "StorageLocation" text NULL,
    "CreatedDate" timestamp without time zone NOT NULL,
    "ModifiedDate" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_ProductVariant" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ProductVariant_Product_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Product" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "UserClaim" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text NULL,
    "ClaimValue" text NULL,
    CONSTRAINT "PK_UserClaim" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserClaim_SystemUser_UserId" FOREIGN KEY ("UserId") REFERENCES "SystemUser" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserLogin" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text NULL,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_UserLogin" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_UserLogin_SystemUser_UserId" FOREIGN KEY ("UserId") REFERENCES "SystemUser" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserRole" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_UserRole" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_UserRole_Role_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Role" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserRole_SystemUser_UserId" FOREIGN KEY ("UserId") REFERENCES "SystemUser" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserToken" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text NULL,
    CONSTRAINT "PK_UserToken" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_UserToken_SystemUser_UserId" FOREIGN KEY ("UserId") REFERENCES "SystemUser" ("Id") ON DELETE CASCADE
);

CREATE TABLE "OrderItem" (
    "Id" text NOT NULL,
    "OrderNumber" text NULL,
    "ProductId" text NULL,
    "Quantity" real NOT NULL,
    "Unit" real NOT NULL,
    "Price" numeric NOT NULL,
    "DiscountAmount" numeric NOT NULL,
    "TotalAmount" numeric NOT NULL,
    "PriceQuoteOrderId" text NULL,
    "PurchaseOrderId" text NULL,
    CONSTRAINT "PK_OrderItem" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OrderItem_PriceQuote_PriceQuoteOrderId" FOREIGN KEY ("PriceQuoteOrderId") REFERENCES "PriceQuote" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_OrderItem_Product_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Product" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_OrderItem_PurchaseOrder_PurchaseOrderId" FOREIGN KEY ("PurchaseOrderId") REFERENCES "PurchaseOrder" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "ProductSerialNumber" (
    "Id" text NOT NULL,
    "ProductId" text NULL,
    "SerialNumber" text NULL,
    "ProductVariantId" text NULL,
    CONSTRAINT "PK_ProductSerialNumber" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ProductSerialNumber_ProductVariant_ProductVariantId" FOREIGN KEY ("ProductVariantId") REFERENCES "ProductVariant" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "VariantValue" (
    "Id" text NOT NULL,
    "ProductVariantId" text NULL,
    "Attribute" text NULL,
    "Value" text NULL,
    CONSTRAINT "PK_VariantValue" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_VariantValue_ProductVariant_ProductVariantId" FOREIGN KEY ("ProductVariantId") REFERENCES "ProductVariant" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_OrderItem_PriceQuoteOrderId" ON "OrderItem" ("PriceQuoteOrderId");

CREATE INDEX "IX_OrderItem_ProductId" ON "OrderItem" ("ProductId");

CREATE INDEX "IX_OrderItem_PurchaseOrderId" ON "OrderItem" ("PurchaseOrderId");

CREATE INDEX "IX_PriceQuote_CreatedById" ON "PriceQuote" ("CreatedById");

CREATE INDEX "IX_PriceQuote_SupplierId" ON "PriceQuote" ("SupplierId");

CREATE INDEX "IX_PriceQuote_TransactionId" ON "PriceQuote" ("TransactionId");

CREATE INDEX "IX_Product_BrandId" ON "Product" ("BrandId");

CREATE INDEX "IX_Product_CategoryId" ON "Product" ("CategoryId");

CREATE INDEX "IX_Product_CreatedById" ON "Product" ("CreatedById");

CREATE INDEX "IX_ProductSerialNumber_ProductVariantId" ON "ProductSerialNumber" ("ProductVariantId");

CREATE INDEX "IX_ProductVariant_ProductId" ON "ProductVariant" ("ProductId");

CREATE INDEX "IX_PurchaseOrder_CreatedById" ON "PurchaseOrder" ("CreatedById");

CREATE INDEX "IX_PurchaseOrder_PriceQuoteOrderId" ON "PurchaseOrder" ("PriceQuoteOrderId");

CREATE INDEX "IX_PurchaseOrder_SupplierId" ON "PurchaseOrder" ("SupplierId");

CREATE INDEX "IX_PurchaseOrder_TransactionId" ON "PurchaseOrder" ("TransactionId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "Role" ("NormalizedName");

CREATE INDEX "IX_RoleClaim_RoleId" ON "RoleClaim" ("RoleId");

CREATE INDEX "EmailIndex" ON "SystemUser" ("NormalizedEmail");

CREATE INDEX "IX_SystemUser_UserInfoId" ON "SystemUser" ("UserInfoId");

CREATE UNIQUE INDEX "UserNameIndex" ON "SystemUser" ("NormalizedUserName");

CREATE INDEX "IX_UserClaim_UserId" ON "UserClaim" ("UserId");

CREATE INDEX "IX_UserLogin_UserId" ON "UserLogin" ("UserId");

CREATE INDEX "IX_UserRole_RoleId" ON "UserRole" ("RoleId");

CREATE INDEX "IX_VariantValue_ProductVariantId" ON "VariantValue" ("ProductVariantId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210601091433_PostgresCreate', '5.0.5');

COMMIT;

